n_estimators: 50
criterion: entropy
max_depth: 50
min_samples_split: 6
min_samples_leaf: 1
min_weight_fraction_leaf: 0.001
max_features: 5
min_impurity_decrease: 0.0
bootstrap: false
class_weight: balanced_subsample
ccp_alpha: 0.0001
